apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    app: {{ .TemplateName }}
spec:
  selector:
    matchLabels:
      app: {{ .TemplateName }}
  replicas: {{ .ReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ .TemplateName }}
    spec:
      volumes: {{ range .Volume }}
      - name: {{ .Name }}
        persistentVolumeClaim:
          claimName: {{ .ClaimName }} {{ end }}
      containers: {{ range .Containers }}
      - name: {{ .Name }}
        image: {{ .Image }}
        ports: {{ range .Ports }}
        - containerPort: {{ . }} {{ end }}
        env: {{ range .Env }}
        - name: {{ .Key }}
          value: {{ .Value }} {{ end }}
        volumeMounts: {{ range .VolumeMount }}
        - name: {{ .Name }}
          mountPath: {{ .MountPath }} {{ end }} {{ end }}