apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Name }}
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .StorageClassName }}
  accessModes: {{ range .AccessMode }}
  - {{ . }} {{ end }}
  resources:
    requests:
      storage: {{ .Capacity }}