apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Name }}
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .StorageClassName }}
  accessModes:
    - {{ .AccessMode }}
  resources:
    requests:
      storage: {{ .Capacity }}