apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Name }}
spec:
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Capacity }}