apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
spec:
  type: {{ .Type }}
  selector:
    app: {{ .TemplateName }}
  ports: {{ range .Ports }}
    - name: {{ .Name }}
      targetPort: {{ .TargetPort }}
      nodePort: {{ .NodePort }}
      port: {{ .ContainerPort }} {{ end }}
      