apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
spec:
  type: {{ .Type }}
  selector:
    app: {{ .TemplateName }}
  ports: {{ range .Ports }}
    - name: {{ .Name }}
      port: {{ .ContainerPort }} 
      targetPort: {{ .TargetPort }} {{ if not (eq .NodePort 0) }}
      nodePort: {{ .NodePort }} {{ end }} {{ end }}